# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

area1 = Area.create(name: 'Barking and Dagenham')
area2 = Area.create(name: 'Barnet')
area3 = Area.create(name: 'Bexley')
area4 = Area.create(name: 'Brent')
area5 = Area.create(name: 'Bromley')
area6 = Area.create(name: 'Camden')
area7 = Area.create(name: 'City of London (central)')
area8 = Area.create(name: 'Croydon')
area9 = Area.create(name: 'Ealing')
area10 = Area.create(name: 'Enfield')
area11 = Area.create(name: 'Greenwich')
area12 = Area.create(name: 'Hackney')
area13 = Area.create(name: 'Hammersmith and Fulham')
area14 = Area.create(name: 'Haringey')
area15 = Area.create(name: 'Harrow')
area16 = Area.create(name: 'Havering')
area17 = Area.create(name: 'Hillingdon')
area18 = Area.create(name: 'Hounslow')
area19 = Area.create(name: 'Islington')
area20 = Area.create(name: 'Kensington and Chelsea')
area21 = Area.create(name: 'Kingston upon Thames')
area22 = Area.create(name: 'Lambeth')
area23 = Area.create(name: 'Lewisham')
area24 = Area.create(name: 'Merton')
area25 = Area.create(name: 'Newham')
area26 = Area.create(name: 'Redbridge')
area27 = Area.create(name: 'Richmond upon Thames')
area28 = Area.create(name: 'Southwark')
area29 = Area.create(name: 'Sutton')
area30 = Area.create(name: 'Tower Hamlets')
area31 = Area.create(name: 'Waltham Forest')
area32 = Area.create(name: 'Wandsworth')
area33 = Area.create(name: 'Westminster')

spec1 = Specialty.create(name: 'Boxing')
spec2 = Specialty.create(name: 'Calisthenics')
spec3 = Specialty.create(name: 'Dietary Advice')
spec3 = Specialty.create(name: 'Golf')
spec4 = Specialty.create(name: 'Gymnastics')
spec5 = Specialty.create(name: 'Kettlebells')
spec6 = Specialty.create(name: 'Kickboxing')
spec7 = Specialty.create(name: 'Life Coach')
spec8 = Specialty.create(name: 'Lower Back Pain Management')
spec9 = Specialty.create(name: 'Meditation')
spec10 = Specialty.create(name: 'Mixed Martial Arts')
spec11 = Specialty.create(name: 'Pilates')
spec12 = Specialty.create(name: 'Post Natal/Pre Natal')
spec13 = Specialty.create(name: 'Postural Correction')
spec14 = Specialty.create(name: 'Power Lifting')
spec15 = Specialty.create(name: 'Running/Track Sports')
spec16 = Specialty.create(name: 'Sports Massage')
spec17 = Specialty.create(name: 'Strength Training')
spec18 = Specialty.create(name: 'Water Sports')
spec19 = Specialty.create(name: 'Weight Training')
spec20 = Specialty.create(name: 'Yoga')
